### ISSUE TITLE
Epic: Basic Styling

### ISSUE THREAD

**Issue by rachel-o-donnell** [rachel-o-donnell/the-witchs-cauldron#30]
Add basic bootstrap style to the following: 
- [x] 1. Styling to Home Page
- [x] 2. Nav bar
- [x] 3. add image and main blurb
- [x] 4. footer
- [x] 5. Styling to Post Page
- [x] 6. Log in/sign up

**Comment by rachel-o-donnell** [comment]
1, 2 and 4 completed Iteration 2

**Comment by rachel-o-donnell** [comment]
5 & 6 done iteration 3

**Comment by rachel-o-donnell** [comment]
# done initeration 6
